language: elixir
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3.2
      env: MIX_ENV=test ELIXIR_ERL_OPTIONS="+T 9"
    - otp_release: 20.0
      elixir: 1.5
      env: MIX_ENV=test ELIXIR_ERL_OPTIONS="+T 9"
before_script:
  - mix deps.get
  - mix compile --warnings-as-errors
script:
  - mix coveralls.travis
  - travis_wait 30 mix dialyzer --halt-exit-status
  - mix credo --strict
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
cache:
  directories:
    - _build
    - deps
